seed: seeds.txt
self_loops: 0
r: 0.7
eta: [0.5,0.5,0]
lamb:
    - [1/3,1/3,1/3]
    - [1/3,1/3,1/3]
    - [1/3,1/3,1/3]
multiplex:
    protein:
        layers:
            - networks/multiplex/1/PPI.gr
            - networks/multiplex/1/Complexes.gr
            - networks/multiplex/1/Reactome.gr
        delta: 0.1
        graph_type: [00, 00, 00]
        tau: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333]
    disease:
        layers:
            - networks/multiplex/2/disease_disease_final.gr
        delta: 0.1
        graph_type: [00]
        tau: [1]
    drug:
        layers:
            - networks/multiplex/3/clinical_drug_interactions.gr
            - networks/multiplex/3/experimental_drug_combinations.gr
            - networks/multiplex/3/predicted_drug_combinations.gr
            - networks/multiplex/3/drugbank-chem-chem.gr
        delta: 0.1
        graph_type: [00, 00, 00, 00]
        tau: [0.25, 0.25, 0.25, 0.25]
bipartite: 
    networks/bipartite/1_2.gr: {source: protein, target: disease, graph_type: 00}
    networks/bipartite/3_1.gr: {source: drug, target: protein, graph_type: 00}
    networks/bipartite/3_2.gr: {source: drug, target: disease, graph_type: 00}
